version: 0.0.{build}

skip_non_tags: true

build:
    verbosity: minimal

platform:
  - x86
  - x64

cache:
  - node_modules
  - bower_components -> bower.json
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 6 $env:PLATFORM
  - npm install bower -g
  - npm install
  - bower install

build_script:
  - node --version
  - IF %PLATFORM% EQU x64 (SET package_arch=x64) ELSE (SET package_arch=ia32)
  - node node_modules\ember-cli\bin\ember electron:package --platform win32 --arch %package_arch% --icon public/assets/icons/win32.ico

after_build:
  - 7z a electron-builds\exercism-gui-win32-%PLATFORM%-%APPVEYOR_REPO_TAG_NAME%.zip electron-builds\exercism-gui-win32-%package_arch%
  - ps: ls electron-builds

artifacts:
  - path: 'electron-builds\*.zip'
    name: electron-package

test: off

deploy:
  provider: GitHub
  auth_token:
    secure: 4Lc+r0RBFpZLKT+JZ5tlHQsEttScYJBtrTQ9BmtYQqcZyXlMP8v/+wjrBRdtY4XO
  artifact: electron-package
  on:
    appveyor_repo_tag: true
